# -*- python -*-
from lsst.sconsUtils import scripts
ignoreList = ["checkPipetteAllMappers.py", "compareBoostToDb.py",
        "fpaFigures.py", "psfPhotometry.py", "testButlerQueries.py",
        "testDbQueries.py"]
scripts.BasicSConscript.tests(ignoreList=ignoreList)
