# -*- python -*-
import re
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions pex_logging pex_policy")
sharedObj = "_"+env.pythonPkg
swigFile = env.pythonPkg + ".i"
env.LoadableModuleIncomplete(sharedObj, swigFile,
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs(env.thisPkg))
