# -*- python -*-
import glob, os, re

Import('env')
#
# Here's a way to to build the files in the list noOptFiles without optimisation
#
ccFiles = glob.glob("../src/*.cc")
try:
    ccFiles = env.SourcesForSharedLibrary(ccFiles)
except AttributeError:                  # requires sconsUtils > 3.3
    pass

env.SharedLibrary(
    'testing_pipeQA', ccFiles, LIBS=[x for x in env.getlibs("testing_pipeQA") if x != "testing_pipeQA"]
)
